language: elixir
env:
  - MIX_ENV=test
matrix:
  include:
    - elixir: 1.6
      otp_release: 20.0
    - elixir: 1.8
      otp_release: 21.0
script:
  - mix deps.compile
  - mix test
after_script:
  - mix credo
  - mix dialyzer --halt-exit-status
